/**
 * Suite 12: Session memory
 * Tests the rolling-summary memory module in backend/memory/session-memory.ts.
 * Tests 1–2 and 4–5 are pure in-memory (no API calls).
 * Test 3 makes a real Haiku API call to verify summarization fires correctly.
 */

import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '../..');

interface TestResult {
  ok: boolean | 'skip';
}

interface Reporter {
  pass: (label: string) => void;
  fail: (label: string, err: string) => void;
  skip: (label: string, reason: string) => void;
  results: TestResult[];
}

export async function checkMemory({ pass, fail, skip, results }: Reporter): Promise<void> {
  const {
    getMemoryContext,
    recordTurn,
    clearMemory,
    getMemorySnapshot,
    backdateForTest,
    cleanMemoryStore,
  } = await import(`${ROOT}/backend/memory/session-memory.ts`);

  const hasApiKey = !!process.env.ANTHROPIC_API_KEY;

  // ── 1. New session has empty memory ─────────────────────────────────────────
  const id1 = `test-mem-${Date.now()}-1`;
  const ctx1 = getMemoryContext(id1);

  if (ctx1.summary === null && Array.isArray(ctx1.rawTurns) && ctx1.rawTurns.length === 0) {
    pass('new session has empty memory (summary=null, rawTurns=[])');
    results.push({ ok: true });
  } else {
    fail('new session has empty memory', `Got: ${JSON.stringify(ctx1)}`);
    results.push({ ok: false });
  }

  // ── 2. recordTurn stores turns synchronously ─────────────────────────────────
  // rawTurns is written synchronously inside recordTurn — no need to wait.
  const id2 = `test-mem-${Date.now()}-2`;
  recordTurn(id2, 'Hello Mewsie', 'Hello! How can I help?');

  const ctx2 = getMemoryContext(id2);
  if (
    ctx2.rawTurns.length === 2 &&
    ctx2.rawTurns[0].role === 'user' &&
    ctx2.rawTurns[0].content === 'Hello Mewsie' &&
    ctx2.rawTurns[1].role === 'assistant' &&
    ctx2.rawTurns[1].content === 'Hello! How can I help?'
  ) {
    pass('recordTurn stores user + assistant messages in order');
    results.push({ ok: true });
  } else {
    fail('recordTurn stores messages', `Got: ${JSON.stringify(ctx2.rawTurns)}`);
    results.push({ ok: false });
  }

  if (ctx2.summary === null) {
    pass('no summary after 1 turn (summarization not triggered yet)');
    results.push({ ok: true });
  } else {
    fail('no summary after 1 turn', `Got summary: ${ctx2.summary}`);
    results.push({ ok: false });
  }

  // ── 3. After 3 turns, summarization fires (real Haiku API call) ──────────────
  if (!hasApiKey) {
    skip('after 3 turns summary is generated', 'ANTHROPIC_API_KEY not set');
    results.push({ ok: 'skip' });
    skip('after summarization rawTurns is empty', 'ANTHROPIC_API_KEY not set');
    results.push({ ok: 'skip' });
  } else {
    const id3 = `test-mem-${Date.now()}-3`;
    recordTurn(id3, 'I use QuickBooks Online', 'Got it — I will keep QuickBooks in mind.');
    recordTurn(id3, 'We are a hotel in Amsterdam', 'Understood, a hotel in Amsterdam using QuickBooks.');
    recordTurn(id3, 'Our tier is Gold', 'Noted — Gold tier support applies to you.');

    // Poll until Haiku summarization resolves (fires in background after 3rd turn).
    const deadline = Date.now() + 10_000;
    while (Date.now() < deadline) {
      const snap = getMemorySnapshot(id3);
      if (snap?.summary) break;
      await new Promise(r => setTimeout(r, 200));
    }

    const snap3 = getMemorySnapshot(id3);
    if (snap3?.summary && snap3.summary.length > 10) {
      pass('after 3 turns a rolling summary is generated by Haiku');
      results.push({ ok: true });
    } else {
      fail('after 3 turns summary is generated', `summary=${JSON.stringify(snap3?.summary)}`);
      results.push({ ok: false });
    }

    if (snap3?.rawTurnCount === 0) {
      pass('after summarization the 3 covered turns are removed from rawTurns');
      results.push({ ok: true });
    } else {
      fail('after summarization rawTurns is empty', `rawTurnCount=${snap3?.rawTurnCount}`);
      results.push({ ok: false });
    }
  }

  // ── 4. clearMemory removes the entry ─────────────────────────────────────────
  const id4 = `test-mem-${Date.now()}-4`;
  recordTurn(id4, 'test', 'response');
  clearMemory(id4);

  const ctx4 = getMemoryContext(id4);
  if (ctx4.summary === null && ctx4.rawTurns.length === 0) {
    pass('clearMemory resets session to empty state');
    results.push({ ok: true });
  } else {
    fail('clearMemory resets session', `Got: ${JSON.stringify(ctx4)}`);
    results.push({ ok: false });
  }

  // ── 5. cleanMemoryStore removes expired entries ──────────────────────────────
  const id5 = `test-mem-${Date.now()}-5`;
  recordTurn(id5, 'hello', 'hi');
  backdateForTest(id5); // set lastActive = 0 (epoch time = definitely expired)
  cleanMemoryStore();

  const afterClean = getMemorySnapshot(id5);
  if (!afterClean) {
    pass('cleanMemoryStore removes entries past TTL');
    results.push({ ok: true });
  } else {
    fail('cleanMemoryStore removes expired entries', 'entry still present after clean');
    results.push({ ok: false });
  }
}
