/**
 * session.ts
 *
 * Manages conversation history and context in memory.
 * Each browser tab gets a unique session ID (generated by the frontend).
 * This file stores the message history and context for each session so
 * Claude remembers what was said earlier in the same conversation.
 *
 * Sessions are stored in a plain JavaScript Map — nothing is written to disk.
 * If the server restarts, all sessions are lost and conversations start fresh.
 *
 * Limits:
 *   - Sessions expire after SESSION_TTL_MINUTES of inactivity
 *   - Only the last SESSION_MAX_PAIRS message pairs are kept
 *   - Expired sessions are cleaned up every 5 minutes
 */

import {
  SESSION_MAX_PAIRS,
  SESSION_TTL_MINUTES,
  LANGUAGE_PERSISTS_ON_TIMEOUT,
} from '../config/Mewsie.config.ts';

// How long a session can be inactive before it is deleted (in milliseconds)
const INACTIVITY_TTL_MS = SESSION_TTL_MINUTES * 60 * 1000;

// How often to run the cleanup that deletes expired sessions (every 5 minutes)
const CLEANUP_INTERVAL_MS = 5 * 60 * 1000;

/**
 * Session object shape:
 * {
 *   history: [],
 *   context: {
 *     language: null,
 *     tools: [],
 *     setupType: null,
 *     lastLoadedDocIds: [],
 *     frustrationCounter: 0,
 *     clarifyRoundCounter: 0,
 *     previousQuestion: null,
 *     clarificationBundles: [],   // completed Q&A rounds, keyed by category IDs
 *   },
 *   lastActive: Date.now(),
 * }
 */

// One completed clarification round: the category IDs that triggered it + all Q&A pairs.
// Keyed by categoryIds so the router can reload relevant context when the same topic recurs.
export interface ClarificationBundle {
  categoryIds: string[];
  qaPairs: { q: string; a: string }[];
}

interface SessionContext {
  language: string | null;
  tools: string[];
  setupType: string | null;
  lastLoadedDocIds: string[];
  frustrationCounter: number;
  // Tracks how many times Stage 2B has chosen Decision A in this session.
  // Hard limit: when this reaches MAX_CLARIFY_ROUNDS, Stage 2B is forced to Decision B.
  clarifyRoundCounter: number;
  previousQuestion: string | null;
  // Stores completed clarification bundles keyed by their matched category IDs.
  // Kept for backward compatibility. New code uses qaLog instead.
  clarificationBundles: ClarificationBundle[];
  // The user's original natural-language question, stored on entering CLARIFY/BASIC mode.
  // Used for re-routing Q&A responses and for Sonnet's queryContext so it knows the
  // original intent rather than just seeing the "Q: ...\nA: ..." formatted string.
  originalQuestion?: string | null;
  // Flat log of all Q&A collected during this session (from BASIC and CLARIFY turns).
  // Built up over the session lifetime. Passed to every stage and mode without exception.
  // Reset to [] on each successful ANSWER turn.
  qaLog: { question: string; answer: string; source: 'BASIC' | 'CLARIFY' }[];
  // Post-answer state — set after every successful ANSWER turn.
  // Cleared when a new unrelated question (Lane B) is detected.
  postAnswerMode: boolean;
  postAnswerSignal: 'COMPLETE' | 'PARTIAL' | null;
  answerContract: {
    topics_covered: string[];
    docs_used: string[];
    open_threads: string[];
  } | null;
  // Snapshot of qaLog at the point of the last successful ANSWER.
  // Used in Lane A so Sonnet retains the clarification context from before the answer.
  qaLogSnapshot: { question: string; answer: string; source: 'BASIC' | 'CLARIFY' }[];
  // True once a Haiku clarifying question has been issued in Lane A.
  // Prevents infinite clarification loops in post-answer mode.
  postAnswerClarifyUsed: boolean;
}

interface Session {
  history: { role: string; content: string }[];
  context: SessionContext;
  lastActive: number;
}

const sessions = new Map<string, Session>();

// ── Private helpers ────────────────────────────────────────────────────────────

function createSession(): Session {
  return {
    history: [],
    context: {
      language: null,
      tools: [],
      setupType: null,
      lastLoadedDocIds: [],
      frustrationCounter: 0,
      clarifyRoundCounter: 0,
      previousQuestion: null,
      clarificationBundles: [],
      originalQuestion: null,
      qaLog: [],
      postAnswerMode: false,
      postAnswerSignal: null,
      answerContract: null,
      qaLogSnapshot: [],
      postAnswerClarifyUsed: false,
    },
    lastActive: Date.now(),
  };
}

// ── Public functions ───────────────────────────────────────────────────────────

// Returns the full session object, creating it if it doesn't exist.
export function getSession(sessionId: string): Session {
  if (!sessions.has(sessionId)) {
    sessions.set(sessionId, createSession());
  } else {
    sessions.get(sessionId)!.lastActive = Date.now();
  }
  return sessions.get(sessionId)!;
}

// Returns session.history — creates the session if it doesn't exist.
export function getHistory(sessionId: string): { role: string; content: string }[] {
  return getSession(sessionId).history;
}

// Appends {role, content} to history. Trims to last SESSION_MAX_PAIRS * 2 messages.
export function addToHistory(sessionId: string, role: string, content: string): void {
  const session = getSession(sessionId);
  session.history.push({ role, content });
  session.lastActive = Date.now();

  // Trim to the last SESSION_MAX_PAIRS pairs (SESSION_MAX_PAIRS * 2 individual messages)
  if (session.history.length > SESSION_MAX_PAIRS * 2) {
    session.history.splice(0, session.history.length - SESSION_MAX_PAIRS * 2);
  }
}

// Returns session.context — creates the session if it doesn't exist.
export function getContext(sessionId: string): SessionContext {
  return getSession(sessionId).context;
}

// Merges patch into session.context using Object.assign.
export function updateContext(sessionId: string, patch: Partial<SessionContext>): void {
  const session = getSession(sessionId);
  Object.assign(session.context, patch);
  session.lastActive = Date.now();
}

// ── Cleanup ────────────────────────────────────────────────────────────────────

// Deletes sessions that have been inactive longer than INACTIVITY_TTL_MS.
// When LANGUAGE_PERSISTS_ON_TIMEOUT is true, logs the language before deleting
// so it can be used for future restoration if needed.
export function cleanSessions(): void {
  const cutoff = Date.now() - INACTIVITY_TTL_MS;
  for (const [id, session] of sessions.entries()) {
    if (session.lastActive < cutoff) {
      if (LANGUAGE_PERSISTS_ON_TIMEOUT && session.context.language) {
        console.log(
          `[session] Expiring session ${id} — language was: ${session.context.language}`
        );
      }
      sessions.delete(id);
    }
  }
}

// Start the cleanup timer. unref() means this timer won't prevent the Node.js
// process from exiting normally if everything else has finished.
const cleanupTimer = setInterval(cleanSessions, CLEANUP_INTERVAL_MS);
cleanupTimer.unref();
