/**
 * session.js
 *
 * Manages conversation history and context in memory.
 * Each browser tab gets a unique session ID (generated by the frontend).
 * This file stores the message history and context for each session so
 * Claude remembers what was said earlier in the same conversation.
 *
 * Sessions are stored in a plain JavaScript Map — nothing is written to disk.
 * If the server restarts, all sessions are lost and conversations start fresh.
 *
 * Limits:
 *   - Sessions expire after SESSION_TTL_MINUTES of inactivity
 *   - Only the last SESSION_MAX_PAIRS message pairs are kept
 *   - Expired sessions are cleaned up every 5 minutes
 */

import {
  SESSION_MAX_PAIRS,
  SESSION_TTL_MINUTES,
  LANGUAGE_PERSISTS_ON_TIMEOUT,
} from '../config/mewsy.config.js';

// How long a session can be inactive before it is deleted (in milliseconds)
const INACTIVITY_TTL_MS = SESSION_TTL_MINUTES * 60 * 1000;

// How often to run the cleanup that deletes expired sessions (every 5 minutes)
const CLEANUP_INTERVAL_MS = 5 * 60 * 1000;

/**
 * Session object shape:
 * {
 *   history: [],
 *   context: {
 *     language: null,
 *     tools: [],
 *     setupType: null,
 *     lastLoadedDocIds: [],
 *     frustrationCounter: 0,
 *     clarifyRoundCounter: 0,
 *     previousQuestion: null,
 *   },
 *   lastActive: Date.now(),
 * }
 */

/** @type {Map<string, { history: {role: string, content: string}[], context: object, lastActive: number }>} */
const sessions = new Map();

// ── Private helpers ────────────────────────────────────────────────────────────

function createSession() {
  return {
    history: [],
    context: {
      language: null,
      tools: [],
      setupType: null,
      lastLoadedDocIds: [],
      frustrationCounter: 0,
      clarifyRoundCounter: 0,
      previousQuestion: null,
    },
    lastActive: Date.now(),
  };
}

// ── Public functions ───────────────────────────────────────────────────────────

// Returns the full session object, creating it if it doesn't exist.
export function getSession(sessionId) {
  if (!sessions.has(sessionId)) {
    sessions.set(sessionId, createSession());
  } else {
    sessions.get(sessionId).lastActive = Date.now();
  }
  return sessions.get(sessionId);
}

// Returns session.history — creates the session if it doesn't exist.
export function getHistory(sessionId) {
  return getSession(sessionId).history;
}

// Appends {role, content} to history. Trims to last SESSION_MAX_PAIRS * 2 messages.
export function addToHistory(sessionId, role, content) {
  const session = getSession(sessionId);
  session.history.push({ role, content });
  session.lastActive = Date.now();

  // Trim to the last SESSION_MAX_PAIRS pairs (SESSION_MAX_PAIRS * 2 individual messages)
  if (session.history.length > SESSION_MAX_PAIRS * 2) {
    session.history.splice(0, session.history.length - SESSION_MAX_PAIRS * 2);
  }
}

// Returns session.context — creates the session if it doesn't exist.
export function getContext(sessionId) {
  return getSession(sessionId).context;
}

// Merges patch into session.context using Object.assign.
export function updateContext(sessionId, patch) {
  const session = getSession(sessionId);
  Object.assign(session.context, patch);
  session.lastActive = Date.now();
}

// ── Cleanup ────────────────────────────────────────────────────────────────────

// Deletes sessions that have been inactive longer than INACTIVITY_TTL_MS.
// When LANGUAGE_PERSISTS_ON_TIMEOUT is true, logs the language before deleting
// so it can be used for future restoration if needed.
export function cleanSessions() {
  const cutoff = Date.now() - INACTIVITY_TTL_MS;
  for (const [id, session] of sessions.entries()) {
    if (session.lastActive < cutoff) {
      if (LANGUAGE_PERSISTS_ON_TIMEOUT && session.context.language) {
        console.log(
          `[session] Expiring session ${id} — language was: ${session.context.language}`
        );
      }
      sessions.delete(id);
    }
  }
}

// Start the cleanup timer. unref() means this timer won't prevent the Node.js
// process from exiting normally if everything else has finished.
const cleanupTimer = setInterval(cleanSessions, CLEANUP_INTERVAL_MS);
cleanupTimer.unref();
